import { defineConfig } from 'tsup';
export default defineConfig({
  entry: [
    'src/index.ts',
    'src/shell.ts',
    'src/http-client.ts',
    'src/file-system.ts',
    'src/browser.ts',
    'src/core/index.ts',
    'src/mcp/index.ts',
    'src/utils/index.ts',
    'src/communication/index.ts',
    'src/productivity/index.ts',
    'src/devtools/index.ts',
    'src/crm/index.ts',
    'src/search/index.ts',
    'src/scraping/index.ts',
    'src/media/index.ts',
    'src/memory/index.ts',
    'src/ai/index.ts',
    'src/data/index.ts',
    'src/finance/index.ts',
    'src/social/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  // Optional peer dependencies — users install only what they need
  external: [
    'nodemailer',
    '@sendgrid/mail',
    'twilio',
    'stripe',
    'pg',
    'mysql2',
    'mysql2/promise',
    'ioredis',
    'playwright',
    'duck-duck-scrape',
    'yahoo-finance2',
  ],
});
